// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod greentic {
    pub mod extension_base {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Kind {
                Design,
                Bundle,
                Deploy,
                Provider,
            }
            impl ::core::fmt::Debug for Kind {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Kind::Design => f.debug_tuple("Kind::Design").finish(),
                        Kind::Bundle => f.debug_tuple("Kind::Bundle").finish(),
                        Kind::Deploy => f.debug_tuple("Kind::Deploy").finish(),
                        Kind::Provider => f.debug_tuple("Kind::Provider").finish(),
                    }
                }
            }
            impl Kind {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Kind {
                    if !cfg!(debug_assertions) {
                        // Generated WIT enum lift uses transmute after the component ABI constrains discriminants; debug builds validate explicitly.
                        // foxguard: ignore[rs/transmute-usage]
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Kind::Design,
                        1 => Kind::Bundle,
                        2 => Kind::Deploy,
                        3 => Kind::Provider,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[derive(Clone)]
            pub struct ExtensionIdentity {
                pub id: _rt::String,
                pub version: _rt::String,
                pub kind: Kind,
            }
            impl ::core::fmt::Debug for ExtensionIdentity {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ExtensionIdentity")
                        .field("id", &self.id)
                        .field("version", &self.version)
                        .field("kind", &self.kind)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct CapabilityRef {
                pub id: _rt::String,
                pub version: _rt::String,
            }
            impl ::core::fmt::Debug for CapabilityRef {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("CapabilityRef")
                        .field("id", &self.id)
                        .field("version", &self.version)
                        .finish()
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Severity {
                Error,
                Warning,
                Info,
                Hint,
            }
            impl ::core::fmt::Debug for Severity {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Severity::Error => f.debug_tuple("Severity::Error").finish(),
                        Severity::Warning => f.debug_tuple("Severity::Warning").finish(),
                        Severity::Info => f.debug_tuple("Severity::Info").finish(),
                        Severity::Hint => f.debug_tuple("Severity::Hint").finish(),
                    }
                }
            }
            impl Severity {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Severity {
                    if !cfg!(debug_assertions) {
                        // Generated WIT enum lift uses transmute after the component ABI constrains discriminants; debug builds validate explicitly.
                        // foxguard: ignore[rs/transmute-usage]
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Severity::Error,
                        1 => Severity::Warning,
                        2 => Severity::Info,
                        3 => Severity::Hint,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[derive(Clone)]
            pub struct Diagnostic {
                pub severity: Severity,
                pub code: _rt::String,
                pub message: _rt::String,
                pub path: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for Diagnostic {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Diagnostic")
                        .field("severity", &self.severity)
                        .field("code", &self.code)
                        .field("message", &self.message)
                        .field("path", &self.path)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub enum ExtensionError {
                InvalidInput(_rt::String),
                MissingCapability(_rt::String),
                PermissionDenied(_rt::String),
                NotFound(_rt::String),
                SchemaInvalid(_rt::String),
                Internal(_rt::String),
            }
            impl ::core::fmt::Debug for ExtensionError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        ExtensionError::InvalidInput(e) => {
                            f.debug_tuple("ExtensionError::InvalidInput")
                                .field(e)
                                .finish()
                        }
                        ExtensionError::MissingCapability(e) => {
                            f.debug_tuple("ExtensionError::MissingCapability")
                                .field(e)
                                .finish()
                        }
                        ExtensionError::PermissionDenied(e) => {
                            f.debug_tuple("ExtensionError::PermissionDenied")
                                .field(e)
                                .finish()
                        }
                        ExtensionError::NotFound(e) => {
                            f.debug_tuple("ExtensionError::NotFound").field(e).finish()
                        }
                        ExtensionError::SchemaInvalid(e) => {
                            f.debug_tuple("ExtensionError::SchemaInvalid")
                                .field(e)
                                .finish()
                        }
                        ExtensionError::Internal(e) => {
                            f.debug_tuple("ExtensionError::Internal").field(e).finish()
                        }
                    }
                }
            }
            impl ::core::fmt::Display for ExtensionError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl std::error::Error for ExtensionError {}
        }
    }
    pub mod extension_host {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod logging {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Level {
                Trace,
                Debug,
                Info,
                Warn,
                Error,
            }
            impl ::core::fmt::Debug for Level {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Level::Trace => f.debug_tuple("Level::Trace").finish(),
                        Level::Debug => f.debug_tuple("Level::Debug").finish(),
                        Level::Info => f.debug_tuple("Level::Info").finish(),
                        Level::Warn => f.debug_tuple("Level::Warn").finish(),
                        Level::Error => f.debug_tuple("Level::Error").finish(),
                    }
                }
            }
            impl Level {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Level {
                    if !cfg!(debug_assertions) {
                        // Generated WIT enum lift uses transmute after the component ABI constrains discriminants; debug builds validate explicitly.
                        // foxguard: ignore[rs/transmute-usage]
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Level::Trace,
                        1 => Level::Debug,
                        2 => Level::Info,
                        3 => Level::Warn,
                        4 => Level::Error,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn log(level: Level, target: &str, message: &str) -> () {
                unsafe {
                    let vec0 = target;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = message;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "greentic:extension-host/logging@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "log"]
                        fn wit_import2(
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import2(
                            level.clone() as i32,
                            ptr0.cast_mut(),
                            len0,
                            ptr1.cast_mut(),
                            len1,
                        )
                    };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn log_kv(
                level: Level,
                target: &str,
                message: &str,
                fields: &[(_rt::String, _rt::String)],
            ) -> () {
                unsafe {
                    let vec0 = target;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = message;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let vec5 = fields;
                    let len5 = vec5.len();
                    let layout5 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec5.len() * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result5 = if layout5.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout5).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout5);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec5.into_iter().enumerate() {
                        let base = result5
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let (t2_0, t2_1) = e;
                            let vec3 = t2_0;
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                            let vec4 = t2_1;
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    }
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "greentic:extension-host/logging@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "log-kv"]
                        fn wit_import6(
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import6(
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import6(
                            level.clone() as i32,
                            ptr0.cast_mut(),
                            len0,
                            ptr1.cast_mut(),
                            len1,
                            result5,
                            len5,
                        )
                    };
                    if layout5.size() != 0 {
                        _rt::alloc::dealloc(result5.cast(), layout5);
                    }
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod greentic {
        pub mod extension_base {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod manifest {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type ExtensionIdentity = super::super::super::super::greentic::extension_base::types::ExtensionIdentity;
                pub type CapabilityRef = super::super::super::super::greentic::extension_base::types::CapabilityRef;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_identity_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_identity();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let super::super::super::super::greentic::extension_base::types::ExtensionIdentity {
                        id: id2,
                        version: version2,
                        kind: kind2,
                    } = result0;
                    let vec3 = (id2.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr1.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    let vec4 = (version2.into_bytes()).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr1.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr1
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr4.cast_mut();
                    *ptr1.add(4 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (kind2
                        .clone() as i32) as u8;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_get_identity<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                    let l2 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l3 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l2, l3, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_offered_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_offered();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec5 = result0;
                    let len5 = vec5.len();
                    let layout5 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec5.len() * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result5 = if layout5.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout5).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout5);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec5.into_iter().enumerate() {
                        let base = result5
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let super::super::super::super::greentic::extension_base::types::CapabilityRef {
                                id: id2,
                                version: version2,
                            } = e;
                            let vec3 = (id2.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                            let vec4 = (version2.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    }
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr1.add(0).cast::<*mut u8>() = result5;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_get_offered<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base6 = l0;
                    let len6 = l1;
                    for i in 0..len6 {
                        let base = base6
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                            let l4 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base6,
                        len6 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_required_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_required();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec5 = result0;
                    let len5 = vec5.len();
                    let layout5 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec5.len() * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result5 = if layout5.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout5).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout5);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec5.into_iter().enumerate() {
                        let base = result5
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let super::super::super::super::greentic::extension_base::types::CapabilityRef {
                                id: id2,
                                version: version2,
                            } = e;
                            let vec3 = (id2.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                            let vec4 = (version2.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    }
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr1.add(0).cast::<*mut u8>() = result5;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_get_required<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base6 = l0;
                    let len6 = l1;
                    for i in 0..len6 {
                        let base = base6
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                            let l4 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base6,
                        len6 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                pub trait Guest {
                    fn get_identity() -> ExtensionIdentity;
                    fn get_offered() -> _rt::Vec<CapabilityRef>;
                    fn get_required() -> _rt::Vec<CapabilityRef>;
                }
                #[doc(hidden)]
                macro_rules! __export_greentic_extension_base_manifest_0_2_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "greentic:extension-base/manifest@0.2.0#get-identity")] unsafe
                        extern "C" fn export_get_identity() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_get_identity_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_greentic:extension-base/manifest@0.2.0#get-identity")]
                        unsafe extern "C" fn _post_return_get_identity(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*:: __post_return_get_identity::<$ty
                        > (arg0) } } #[unsafe (export_name =
                        "greentic:extension-base/manifest@0.2.0#get-offered")] unsafe
                        extern "C" fn export_get_offered() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_get_offered_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_greentic:extension-base/manifest@0.2.0#get-offered")]
                        unsafe extern "C" fn _post_return_get_offered(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_get_offered::<$ty >
                        (arg0) } } #[unsafe (export_name =
                        "greentic:extension-base/manifest@0.2.0#get-required")] unsafe
                        extern "C" fn export_get_required() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_get_required_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_greentic:extension-base/manifest@0.2.0#get-required")]
                        unsafe extern "C" fn _post_return_get_required(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*:: __post_return_get_required::<$ty
                        > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_greentic_extension_base_manifest_0_2_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 5 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 5
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod lifecycle {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type ExtensionError = super::super::super::super::greentic::extension_base::types::ExtensionError;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_init_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::init(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(_) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            use super::super::super::super::greentic::extension_base::types::ExtensionError as V9;
                            match e {
                                V9::InvalidInput(e) => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                    let vec3 = (e.into_bytes()).into_boxed_slice();
                                    let ptr3 = vec3.as_ptr().cast::<u8>();
                                    let len3 = vec3.len();
                                    ::core::mem::forget(vec3);
                                    *ptr2
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len3;
                                    *ptr2
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr3.cast_mut();
                                }
                                V9::MissingCapability(e) => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec4 = (e.into_bytes()).into_boxed_slice();
                                    let ptr4 = vec4.as_ptr().cast::<u8>();
                                    let len4 = vec4.len();
                                    ::core::mem::forget(vec4);
                                    *ptr2
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len4;
                                    *ptr2
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr4.cast_mut();
                                }
                                V9::PermissionDenied(e) => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (2i32) as u8;
                                    let vec5 = (e.into_bytes()).into_boxed_slice();
                                    let ptr5 = vec5.as_ptr().cast::<u8>();
                                    let len5 = vec5.len();
                                    ::core::mem::forget(vec5);
                                    *ptr2
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len5;
                                    *ptr2
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr5.cast_mut();
                                }
                                V9::NotFound(e) => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (3i32) as u8;
                                    let vec6 = (e.into_bytes()).into_boxed_slice();
                                    let ptr6 = vec6.as_ptr().cast::<u8>();
                                    let len6 = vec6.len();
                                    ::core::mem::forget(vec6);
                                    *ptr2
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len6;
                                    *ptr2
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr6.cast_mut();
                                }
                                V9::SchemaInvalid(e) => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (4i32) as u8;
                                    let vec7 = (e.into_bytes()).into_boxed_slice();
                                    let ptr7 = vec7.as_ptr().cast::<u8>();
                                    let len7 = vec7.len();
                                    ::core::mem::forget(vec7);
                                    *ptr2
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len7;
                                    *ptr2
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr7.cast_mut();
                                }
                                V9::Internal(e) => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (5i32) as u8;
                                    let vec8 = (e.into_bytes()).into_boxed_slice();
                                    let ptr8 = vec8.as_ptr().cast::<u8>();
                                    let len8 = vec8.len();
                                    ::core::mem::forget(vec8);
                                    *ptr2
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len8;
                                    *ptr2
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr8.cast_mut();
                                }
                            }
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_init<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = i32::from(
                                *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                            );
                            match l1 {
                                0 => {
                                    let l2 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l3 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l2, l3, 1);
                                }
                                1 => {
                                    let l4 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l5 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l4, l5, 1);
                                }
                                2 => {
                                    let l6 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l7 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l6, l7, 1);
                                }
                                3 => {
                                    let l8 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l9 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l8, l9, 1);
                                }
                                4 => {
                                    let l10 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l11 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l10, l11, 1);
                                }
                                _ => {
                                    let l12 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l13 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l12, l13, 1);
                                }
                            }
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_shutdown_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::shutdown();
                }
                pub trait Guest {
                    fn init(config_json: _rt::String) -> Result<(), ExtensionError>;
                    fn shutdown() -> ();
                }
                #[doc(hidden)]
                macro_rules! __export_greentic_extension_base_lifecycle_0_2_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "greentic:extension-base/lifecycle@0.2.0#init")] unsafe extern
                        "C" fn export_init(arg0 : * mut u8, arg1 : usize,) -> * mut u8 {
                        unsafe { $($path_to_types)*:: _export_init_cabi::<$ty > (arg0,
                        arg1) } } #[unsafe (export_name =
                        "cabi_post_greentic:extension-base/lifecycle@0.2.0#init")] unsafe
                        extern "C" fn _post_return_init(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_init::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "greentic:extension-base/lifecycle@0.2.0#shutdown")] unsafe
                        extern "C" fn export_shutdown() { unsafe { $($path_to_types)*::
                        _export_shutdown_cabi::<$ty > () } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_greentic_extension_base_lifecycle_0_2_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
        pub mod extension_design {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod guardrail {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum Direction {
                    Inbound,
                    Outbound,
                }
                impl ::core::fmt::Debug for Direction {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            Direction::Inbound => {
                                f.debug_tuple("Direction::Inbound").finish()
                            }
                            Direction::Outbound => {
                                f.debug_tuple("Direction::Outbound").finish()
                            }
                        }
                    }
                }
                impl Direction {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> Direction {
                        if !cfg!(debug_assertions) {
                            // Generated WIT enum lift uses transmute after the component ABI constrains discriminants; debug builds validate explicitly.
                            // foxguard: ignore[rs/transmute-usage]
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => Direction::Inbound,
                            1 => Direction::Outbound,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                #[derive(Clone)]
                pub struct GuardrailInput {
                    pub direction: Direction,
                    pub content: _rt::String,
                    pub agent_id: _rt::String,
                    pub session_id: _rt::String,
                    pub tenant_id: _rt::String,
                    pub env_id: _rt::String,
                    pub context: Option<_rt::String>,
                }
                impl ::core::fmt::Debug for GuardrailInput {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("GuardrailInput")
                            .field("direction", &self.direction)
                            .field("content", &self.content)
                            .field("agent-id", &self.agent_id)
                            .field("session-id", &self.session_id)
                            .field("tenant-id", &self.tenant_id)
                            .field("env-id", &self.env_id)
                            .field("context", &self.context)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct DenyInfo {
                    pub code: _rt::String,
                    pub message: _rt::String,
                    pub details: Option<_rt::String>,
                }
                impl ::core::fmt::Debug for DenyInfo {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("DenyInfo")
                            .field("code", &self.code)
                            .field("message", &self.message)
                            .field("details", &self.details)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub enum Verdict {
                    Accept,
                    Update(_rt::String),
                    Deny(DenyInfo),
                }
                impl ::core::fmt::Debug for Verdict {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            Verdict::Accept => f.debug_tuple("Verdict::Accept").finish(),
                            Verdict::Update(e) => {
                                f.debug_tuple("Verdict::Update").field(e).finish()
                            }
                            Verdict::Deny(e) => {
                                f.debug_tuple("Verdict::Deny").field(e).finish()
                            }
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_evaluate_cabi<T: Guest>(
                    arg0: i32,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: *mut u8,
                    arg4: usize,
                    arg5: *mut u8,
                    arg6: usize,
                    arg7: *mut u8,
                    arg8: usize,
                    arg9: *mut u8,
                    arg10: usize,
                    arg11: i32,
                    arg12: *mut u8,
                    arg13: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let len1 = arg4;
                    let bytes1 = _rt::Vec::from_raw_parts(arg3.cast(), len1, len1);
                    let len2 = arg6;
                    let bytes2 = _rt::Vec::from_raw_parts(arg5.cast(), len2, len2);
                    let len3 = arg8;
                    let bytes3 = _rt::Vec::from_raw_parts(arg7.cast(), len3, len3);
                    let len4 = arg10;
                    let bytes4 = _rt::Vec::from_raw_parts(arg9.cast(), len4, len4);
                    let result6 = T::evaluate(GuardrailInput {
                        direction: Direction::_lift(arg0 as u8),
                        content: _rt::string_lift(bytes0),
                        agent_id: _rt::string_lift(bytes1),
                        session_id: _rt::string_lift(bytes2),
                        tenant_id: _rt::string_lift(bytes3),
                        env_id: _rt::string_lift(bytes4),
                        context: match arg11 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len5 = arg13;
                                    let bytes5 = _rt::Vec::from_raw_parts(
                                        arg12.cast(),
                                        len5,
                                        len5,
                                    );
                                    _rt::string_lift(bytes5)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    });
                    let ptr7 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result6 {
                        Verdict::Accept => {
                            *ptr7.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Verdict::Update(e) => {
                            *ptr7.add(0).cast::<u8>() = (1i32) as u8;
                            let vec8 = (e.into_bytes()).into_boxed_slice();
                            let ptr8 = vec8.as_ptr().cast::<u8>();
                            let len8 = vec8.len();
                            ::core::mem::forget(vec8);
                            *ptr7
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len8;
                            *ptr7
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr8.cast_mut();
                        }
                        Verdict::Deny(e) => {
                            *ptr7.add(0).cast::<u8>() = (2i32) as u8;
                            let DenyInfo {
                                code: code9,
                                message: message9,
                                details: details9,
                            } = e;
                            let vec10 = (code9.into_bytes()).into_boxed_slice();
                            let ptr10 = vec10.as_ptr().cast::<u8>();
                            let len10 = vec10.len();
                            ::core::mem::forget(vec10);
                            *ptr7
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len10;
                            *ptr7
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr10.cast_mut();
                            let vec11 = (message9.into_bytes()).into_boxed_slice();
                            let ptr11 = vec11.as_ptr().cast::<u8>();
                            let len11 = vec11.len();
                            ::core::mem::forget(vec11);
                            *ptr7
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len11;
                            *ptr7
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr11.cast_mut();
                            match details9 {
                                Some(e) => {
                                    *ptr7
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec12 = (e.into_bytes()).into_boxed_slice();
                                    let ptr12 = vec12.as_ptr().cast::<u8>();
                                    let len12 = vec12.len();
                                    ::core::mem::forget(vec12);
                                    *ptr7
                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len12;
                                    *ptr7
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr12.cast_mut();
                                }
                                None => {
                                    *ptr7
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                        }
                    }
                    ptr7
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_evaluate<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        1 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                            let l5 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l6 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l5, l6, 1);
                            let l7 = i32::from(
                                *arg0
                                    .add(5 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l7 {
                                0 => {}
                                _ => {
                                    let l8 = *arg0
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l9 = *arg0
                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l8, l9, 1);
                                }
                            }
                        }
                    }
                }
                pub trait Guest {
                    fn evaluate(input: GuardrailInput) -> Verdict;
                }
                #[doc(hidden)]
                macro_rules! __export_greentic_extension_design_guardrail_0_3_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "greentic:extension-design/guardrail@0.3.0#evaluate")] unsafe
                        extern "C" fn export_evaluate(arg0 : i32, arg1 : * mut u8, arg2 :
                        usize, arg3 : * mut u8, arg4 : usize, arg5 : * mut u8, arg6 :
                        usize, arg7 : * mut u8, arg8 : usize, arg9 : * mut u8, arg10 :
                        usize, arg11 : i32, arg12 : * mut u8, arg13 : usize,) -> * mut u8
                        { unsafe { $($path_to_types)*:: _export_evaluate_cabi::<$ty >
                        (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9,
                        arg10, arg11, arg12, arg13) } } #[unsafe (export_name =
                        "cabi_post_greentic:extension-design/guardrail@0.3.0#evaluate")]
                        unsafe extern "C" fn _post_return_evaluate(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_evaluate::<$ty >
                        (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_greentic_extension_design_guardrail_0_3_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 8 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 8
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::alloc;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_guardrail_topic_extension_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::greentic::extension_base::manifest::__export_greentic_extension_base_manifest_0_2_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::greentic::extension_base::manifest); $($path_to_types_root)*::
        exports::greentic::extension_base::lifecycle::__export_greentic_extension_base_lifecycle_0_2_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::greentic::extension_base::lifecycle); $($path_to_types_root)*::
        exports::greentic::extension_design::guardrail::__export_greentic_extension_design_guardrail_0_3_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::greentic::extension_design::guardrail);
    };
}
#[doc(inline)]
pub(crate) use __export_guardrail_topic_extension_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.41.0:greentic:guardrail-topic@0.1.0:guardrail-topic-extension:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1419] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xfb\x09\x01A\x02\x01\
A\x0d\x01B\x0d\x01m\x04\x06design\x06bundle\x06deploy\x08provider\x04\0\x04kind\x03\
\0\0\x01r\x03\x02ids\x07versions\x04kind\x01\x04\0\x12extension-identity\x03\0\x02\
\x01r\x02\x02ids\x07versions\x04\0\x0ecapability-ref\x03\0\x04\x01m\x04\x05error\
\x07warning\x04info\x04hint\x04\0\x08severity\x03\0\x06\x01ks\x01r\x04\x08severi\
ty\x07\x04codes\x07messages\x04path\x08\x04\0\x0adiagnostic\x03\0\x09\x01q\x06\x0d\
invalid-input\x01s\0\x12missing-capability\x01s\0\x11permission-denied\x01s\0\x09\
not-found\x01s\0\x0eschema-invalid\x01s\0\x08internal\x01s\0\x04\0\x0fextension-\
error\x03\0\x0b\x03\0#greentic:extension-base/types@0.2.0\x05\0\x01B\x08\x01m\x05\
\x05trace\x05debug\x04info\x04warn\x05error\x04\0\x05level\x03\0\0\x01@\x03\x05l\
evel\x01\x06targets\x07messages\x01\0\x04\0\x03log\x01\x02\x01o\x02ss\x01p\x03\x01\
@\x04\x05level\x01\x06targets\x07messages\x06fields\x04\x01\0\x04\0\x06log-kv\x01\
\x05\x03\0%greentic:extension-host/logging@0.1.0\x05\x01\x02\x03\0\0\x12extensio\
n-identity\x02\x03\0\0\x0ecapability-ref\x01B\x0a\x02\x03\x02\x01\x02\x04\0\x12e\
xtension-identity\x03\0\0\x02\x03\x02\x01\x03\x04\0\x0ecapability-ref\x03\0\x02\x01\
@\0\0\x01\x04\0\x0cget-identity\x01\x04\x01p\x03\x01@\0\0\x05\x04\0\x0bget-offer\
ed\x01\x06\x04\0\x0cget-required\x01\x06\x04\0&greentic:extension-base/manifest@\
0.2.0\x05\x04\x02\x03\0\0\x0fextension-error\x01B\x07\x02\x03\x02\x01\x05\x04\0\x0f\
extension-error\x03\0\0\x01j\0\x01\x01\x01@\x01\x0bconfig-jsons\0\x02\x04\0\x04i\
nit\x01\x03\x01@\0\x01\0\x04\0\x08shutdown\x01\x04\x04\0'greentic:extension-base\
/lifecycle@0.2.0\x05\x06\x01B\x0b\x01m\x02\x07inbound\x08outbound\x04\0\x09direc\
tion\x03\0\0\x01ks\x01r\x07\x09direction\x01\x07contents\x08agent-ids\x0asession\
-ids\x09tenant-ids\x06env-ids\x07context\x02\x04\0\x0fguardrail-input\x03\0\x03\x01\
r\x03\x04codes\x07messages\x07details\x02\x04\0\x09deny-info\x03\0\x05\x01q\x03\x06\
accept\0\0\x06update\x01s\0\x04deny\x01\x06\0\x04\0\x07verdict\x03\0\x07\x01@\x01\
\x05input\x04\0\x08\x04\0\x08evaluate\x01\x09\x04\0)greentic:extension-design/gu\
ardrail@0.3.0\x05\x07\x04\08greentic:guardrail-topic/guardrail-topic-extension@0\
.1.0\x04\0\x0b\x1f\x01\0\x19guardrail-topic-extension\x03\0\0\0G\x09producers\x01\
\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
