// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod greentic {
        pub mod component {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod component_descriptor {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_component_info_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_component_info();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_get_component_info<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_describe_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::describe();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_describe<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 1, 1);
                }
                pub trait Guest {
                    fn get_component_info() -> _rt::Vec<u8>;
                    fn describe() -> _rt::Vec<u8>;
                }
                #[doc(hidden)]
                macro_rules! __export_greentic_component_component_descriptor_0_6_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "greentic:component/component-descriptor@0.6.0#get-component-info")]
                        unsafe extern "C" fn export_get_component_info() -> * mut u8 {
                        unsafe { $($path_to_types)*::
                        _export_get_component_info_cabi::<$ty > () } } #[unsafe
                        (export_name =
                        "cabi_post_greentic:component/component-descriptor@0.6.0#get-component-info")]
                        unsafe extern "C" fn _post_return_get_component_info(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_get_component_info::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "greentic:component/component-descriptor@0.6.0#describe")] unsafe
                        extern "C" fn export_describe() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_describe_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_greentic:component/component-descriptor@0.6.0#describe")]
                        unsafe extern "C" fn _post_return_describe(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_describe::<$ty >
                        (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_greentic_component_component_descriptor_0_6_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod component_schema {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_input_schema_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::input_schema();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_input_schema<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_output_schema_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::output_schema();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_output_schema<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_config_schema_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::config_schema();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_config_schema<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 1, 1);
                }
                pub trait Guest {
                    fn input_schema() -> _rt::Vec<u8>;
                    fn output_schema() -> _rt::Vec<u8>;
                    fn config_schema() -> _rt::Vec<u8>;
                }
                #[doc(hidden)]
                macro_rules! __export_greentic_component_component_schema_0_6_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "greentic:component/component-schema@0.6.0#input-schema")] unsafe
                        extern "C" fn export_input_schema() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_input_schema_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_greentic:component/component-schema@0.6.0#input-schema")]
                        unsafe extern "C" fn _post_return_input_schema(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*:: __post_return_input_schema::<$ty
                        > (arg0) } } #[unsafe (export_name =
                        "greentic:component/component-schema@0.6.0#output-schema")]
                        unsafe extern "C" fn export_output_schema() -> * mut u8 { unsafe
                        { $($path_to_types)*:: _export_output_schema_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_greentic:component/component-schema@0.6.0#output-schema")]
                        unsafe extern "C" fn _post_return_output_schema(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*:: __post_return_output_schema::<$ty
                        > (arg0) } } #[unsafe (export_name =
                        "greentic:component/component-schema@0.6.0#config-schema")]
                        unsafe extern "C" fn export_config_schema() -> * mut u8 { unsafe
                        { $($path_to_types)*:: _export_config_schema_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_greentic:component/component-schema@0.6.0#config-schema")]
                        unsafe extern "C" fn _post_return_config_schema(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*:: __post_return_config_schema::<$ty
                        > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_greentic_component_component_schema_0_6_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod component_runtime {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[derive(Clone)]
                pub struct RunResult {
                    pub output: _rt::Vec<u8>,
                    pub new_state: _rt::Vec<u8>,
                }
                impl ::core::fmt::Debug for RunResult {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("RunResult")
                            .field("output", &self.output)
                            .field("new-state", &self.new_state)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_run_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let len1 = arg3;
                    let result2 = T::run(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                        _rt::Vec::from_raw_parts(arg2.cast(), len1, len1),
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let RunResult { output: output4, new_state: new_state4 } = result2;
                    let vec5 = (output4).into_boxed_slice();
                    let ptr5 = vec5.as_ptr().cast::<u8>();
                    let len5 = vec5.len();
                    ::core::mem::forget(vec5);
                    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr3.add(0).cast::<*mut u8>() = ptr5.cast_mut();
                    let vec6 = (new_state4).into_boxed_slice();
                    let ptr6 = vec6.as_ptr().cast::<u8>();
                    let len6 = vec6.len();
                    ::core::mem::forget(vec6);
                    *ptr3.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
                    *ptr3
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr6.cast_mut();
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_run<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 1, 1);
                    let l3 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l4 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base5 = l3;
                    let len5 = l4;
                    _rt::cabi_dealloc(base5, len5 * 1, 1);
                }
                pub trait Guest {
                    fn run(input: _rt::Vec<u8>, state: _rt::Vec<u8>) -> RunResult;
                }
                #[doc(hidden)]
                macro_rules! __export_greentic_component_component_runtime_0_6_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "greentic:component/component-runtime@0.6.0#run")] unsafe extern
                        "C" fn export_run(arg0 : * mut u8, arg1 : usize, arg2 : * mut u8,
                        arg3 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_run_cabi::<$ty > (arg0, arg1, arg2, arg3) } } #[unsafe
                        (export_name =
                        "cabi_post_greentic:component/component-runtime@0.6.0#run")]
                        unsafe extern "C" fn _post_return_run(arg0 : * mut u8,) { unsafe
                        { $($path_to_types)*:: __post_return_run::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_greentic_component_component_runtime_0_6_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod component_qa {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum QaMode {
                    Default,
                    Setup,
                    Update,
                    Remove,
                }
                impl ::core::fmt::Debug for QaMode {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            QaMode::Default => f.debug_tuple("QaMode::Default").finish(),
                            QaMode::Setup => f.debug_tuple("QaMode::Setup").finish(),
                            QaMode::Update => f.debug_tuple("QaMode::Update").finish(),
                            QaMode::Remove => f.debug_tuple("QaMode::Remove").finish(),
                        }
                    }
                }
                impl QaMode {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> QaMode {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => QaMode::Default,
                            1 => QaMode::Setup,
                            2 => QaMode::Update,
                            3 => QaMode::Remove,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_qa_spec_cabi<T: Guest>(arg0: i32) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::qa_spec(QaMode::_lift(arg0 as u8));
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_qa_spec<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_apply_answers_cabi<T: Guest>(
                    arg0: i32,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: *mut u8,
                    arg4: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let len1 = arg4;
                    let result2 = T::apply_answers(
                        QaMode::_lift(arg0 as u8),
                        _rt::Vec::from_raw_parts(arg1.cast(), len0, len0),
                        _rt::Vec::from_raw_parts(arg3.cast(), len1, len1),
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec4 = (result2).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr3.add(0).cast::<*mut u8>() = ptr4.cast_mut();
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_apply_answers<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 1, 1);
                }
                pub trait Guest {
                    fn qa_spec(mode: QaMode) -> _rt::Vec<u8>;
                    fn apply_answers(
                        mode: QaMode,
                        current_config: _rt::Vec<u8>,
                        answers: _rt::Vec<u8>,
                    ) -> _rt::Vec<u8>;
                }
                #[doc(hidden)]
                macro_rules! __export_greentic_component_component_qa_0_6_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "greentic:component/component-qa@0.6.0#qa-spec")] unsafe extern
                        "C" fn export_qa_spec(arg0 : i32,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_qa_spec_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "cabi_post_greentic:component/component-qa@0.6.0#qa-spec")]
                        unsafe extern "C" fn _post_return_qa_spec(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_qa_spec::<$ty >
                        (arg0) } } #[unsafe (export_name =
                        "greentic:component/component-qa@0.6.0#apply-answers")] unsafe
                        extern "C" fn export_apply_answers(arg0 : i32, arg1 : * mut u8,
                        arg2 : usize, arg3 : * mut u8, arg4 : usize,) -> * mut u8 {
                        unsafe { $($path_to_types)*:: _export_apply_answers_cabi::<$ty >
                        (arg0, arg1, arg2, arg3, arg4) } } #[unsafe (export_name =
                        "cabi_post_greentic:component/component-qa@0.6.0#apply-answers")]
                        unsafe extern "C" fn _post_return_apply_answers(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*:: __post_return_apply_answers::<$ty
                        > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_greentic_component_component_qa_0_6_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod component_i18n {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_i18n_keys_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::i18n_keys();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec3 = result0;
                    let len3 = vec3.len();
                    let layout3 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec3.len() * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result3 = if layout3.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout3).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout3);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec3.into_iter().enumerate() {
                        let base = result3
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let vec2 = (e.into_bytes()).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *base.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                        }
                    }
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr1.add(0).cast::<*mut u8>() = result3;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_i18n_keys<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base4 = l0;
                    let len4 = l1;
                    for i in 0..len4 {
                        let base = base4
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base4,
                        len4 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                pub trait Guest {
                    fn i18n_keys() -> _rt::Vec<_rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_greentic_component_component_i18n_0_6_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "greentic:component/component-i18n@0.6.0#i18n-keys")] unsafe
                        extern "C" fn export_i18n_keys() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_i18n_keys_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_greentic:component/component-i18n@0.6.0#i18n-keys")]
                        unsafe extern "C" fn _post_return_i18n_keys(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_i18n_keys::<$ty >
                        (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_greentic_component_component_i18n_0_6_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::vec::Vec;
    pub use alloc_crate::alloc;
    pub use alloc_crate::string::String;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_component_v0_v6_v0_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::greentic::component::component_descriptor::__export_greentic_component_component_descriptor_0_6_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::greentic::component::component_descriptor); $($path_to_types_root)*::
        exports::greentic::component::component_schema::__export_greentic_component_component_schema_0_6_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::greentic::component::component_schema); $($path_to_types_root)*::
        exports::greentic::component::component_runtime::__export_greentic_component_component_runtime_0_6_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::greentic::component::component_runtime); $($path_to_types_root)*::
        exports::greentic::component::component_qa::__export_greentic_component_component_qa_0_6_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::greentic::component::component_qa); $($path_to_types_root)*::
        exports::greentic::component::component_i18n::__export_greentic_component_component_i18n_0_6_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::greentic::component::component_i18n);
    };
}
#[doc(inline)]
pub(crate) use __export_component_v0_v6_v0_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:greentic:component@0.6.0:component-v0-v6-v0:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 754] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xe9\x04\x01A\x02\x01\
A\x0a\x01B\x04\x01p}\x01@\0\0\0\x04\0\x12get-component-info\x01\x01\x04\0\x08des\
cribe\x01\x01\x04\0-greentic:component/component-descriptor@0.6.0\x05\0\x01B\x05\
\x01p}\x01@\0\0\0\x04\0\x0cinput-schema\x01\x01\x04\0\x0doutput-schema\x01\x01\x04\
\0\x0dconfig-schema\x01\x01\x04\0)greentic:component/component-schema@0.6.0\x05\x01\
\x01B\x05\x01p}\x01r\x02\x06output\0\x09new-state\0\x04\0\x0arun-result\x03\0\x01\
\x01@\x02\x05input\0\x05state\0\0\x02\x04\0\x03run\x01\x03\x04\0*greentic:compon\
ent/component-runtime@0.6.0\x05\x02\x01B\x07\x01m\x04\x07default\x05setup\x06upd\
ate\x06remove\x04\0\x07qa-mode\x03\0\0\x01p}\x01@\x01\x04mode\x01\0\x02\x04\0\x07\
qa-spec\x01\x03\x01@\x03\x04mode\x01\x0ecurrent-config\x02\x07answers\x02\0\x02\x04\
\0\x0dapply-answers\x01\x04\x04\0%greentic:component/component-qa@0.6.0\x05\x03\x01\
B\x03\x01ps\x01@\0\0\0\x04\0\x09i18n-keys\x01\x01\x04\0'greentic:component/compo\
nent-i18n@0.6.0\x05\x04\x04\0+greentic:component/component-v0-v6-v0@0.6.0\x04\0\x0b\
\x18\x01\0\x12component-v0-v6-v0\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\
\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
